### ISSUE TITLE
Twig_Filter_Method is deprecated

### ISSUE THREAD

**Issue by KoenPasman** [teraone/twig-strftime-extension#1]
Using the extension on Symfony 3.3.4 and Twig 1.34.4 I get the following warning in the Profiler:

> User Deprecated: Using an instance of "Twig_Filter_Method" for filter "strftime" is deprecated since version 1.21. Use Twig_SimpleFilter instead.

**Comment by KoenPasman** [comment]
#2 PR provided

**Comment by rechl** [comment]
Thanks for your PR!
I will check test and merge  on this Weekend!

**Comment by nicodemuz** [comment]
@sgotre can we merge this in?

**Comment by rechl** [comment]
Sorry for the delays. Version 1.1.0 is online now
