### ISSUE TITLE
Add support for twig 2

### ISSUE THREAD

**Issue by nicodemuz** [teraone/twig-strftime-extension#5]
Current composer.json seems to be tied with twig version 1. Possible to make it work for twig 2?

**Comment by nicodemuz** [comment]
There seems to be one commit for this already:
https://github.com/proArtex/twig-strftime-extension/commit/7ff98d1f30dfb22a2a57b7835afe8904ffdf09fc

**Comment by rechl** [comment]
@MrNicodemuz Thanks. i have just created a new version

**Comment by nicodemuz** [comment]
@sgotre thank you! Tested and works nicely! :)
